{
 "title": "PiJardin",
 "time": { "from": "2026-06-28T12:43:22.116Z", "to": "2026-06-29T04:09:38.332Z" },
 "panels": [
  {
   "title": "Volume actuel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"puit\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"height_measure\")\r\n  |> map(fn: (r) => ({ r with _value: (220.0 - r._value) * 0.04 }))\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Historique semaine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"puit\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) => r._measurement == \"height_measure\")\r\n  |> map(fn: (r) => ({ r with _value: (220.0 - r._value) * 0.04 }))\r\n  |> drop(columns: [\"hour\", \"minute\", \"resampled\", \"midnight\"])"
    }
   ]
  },
  {
   "title": "Historique 3 jours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"puit\")\r\n  |> range(start: -3d)\r\n  |> filter(fn: (r) => r._measurement == \"height_measure\")\r\n  |> map(fn: (r) => ({ r with _value: (220.0 - r._value) * 0.04 }))\r\n  |> drop(columns: [\"hour\", \"minute\", \"resampled\", \"midnight\"])"
    }
   ]
  }
 ]
}